# Generated by Django 2.2.7 on 2019-12-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='Longitude Coordinate for Squirrel sighting point', max_length=100)),
                ('Y', models.FloatField(help_text='Latitude Coordinate for Squirrel sighting point', max_length=100)),
                ('UID', models.CharField(help_text='Identification tag for Squirrel sighting', max_length=100)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Squirrel sighting session morning or late afternoon', max_length=100)),
                ('Date', models.DateField(help_text='Session of sighting day and month', max_length=100)),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Value is either adult or juvenile', max_length=100)),
                ('Primary_Fur_Color', models.CharField(blank=True, help_text='fur color of squirrel', max_length=100)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='sighter instructed squirrel location', max_length=50)),
                ('Specific_Location', models.CharField(blank=True, help_text='sighter commentary on  squirrel location', max_length=200)),
                ('Running', models.BooleanField(help_text='Squirrel was seen running', max_length=10)),
                ('Chasing', models.BooleanField(help_text='Squirrel was seen chasing', max_length=10)),
                ('Climbing', models.BooleanField(help_text='Squirrel was seen climbing', max_length=10)),
                ('Eating', models.BooleanField(help_text='Squirrel was seen eating', max_length=10)),
                ('Foraging', models.BooleanField(help_text='Squirrel was seen foraging for food', max_length=10)),
                ('Other_activities', models.CharField(blank=True, help_text='no description available ', max_length=200)),
                ('Kuks', models.BooleanField(help_text='Squirrel was heard kukking, a chirpy vocal communication', max_length=10)),
                ('Quaas', models.BooleanField(help_text='Squirrel was heard quaaing, an elongated vocal communication', max_length=10)),
                ('Moans', models.BooleanField(help_text='Squirrel was heard moaning, a high-pitched vocal communication', max_length=10)),
                ('Tail_flags', models.BooleanField(help_text='Squirrel was seen flagging its tail', max_length=10)),
                ('Tail_twitches', models.BooleanField(help_text='Squirrel was seen twitching its tail', max_length=10)),
                ('Approaches', models.BooleanField(help_text='Squirrel was seen approaching human, seeking food', max_length=10)),
                ('Indifferent', models.BooleanField(help_text='Squirrel was indifferent to human presence', max_length=10)),
                ('Runs_From', models.BooleanField(help_text='Squirrel was seen running from humans, seeing them as a threat', max_length=10)),
            ],
        ),
    ]
