# Generated by Django 2.2.7 on 2019-12-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.IntegerField(help_text='Session of sighting day and month'),
        ),
    ]
