# Generated by Django 2.2.7 on 2019-12-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_auto_20191205_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Value is either adult or juvenile', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Squirrel was seen approaching human, seeking food', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Squirrel was seen chasing', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Squirrel was seen climbing', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Squirrel was seen eating', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Squirrel was seen foraging for food', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Squirrel was indifferent to human presence', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='Squirrel was heard kukking, a chirpy vocal communication', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False, help_text='Squirrel was heard moaning, a high-pitched vocal communication', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='fur color of squirrel', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='Squirrel was heard quaaing, an elongated vocal communication', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False, help_text='Squirrel was seen running', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_From',
            field=models.BooleanField(default=False, help_text='Squirrel was seen running from humans, seeing them as a threat', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Squirrel sighting session morning or late afternoon', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.BooleanField(default=False, help_text='Squirrel was seen flagging its tail', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.BooleanField(default=False, help_text='Squirrel was seen twitching its tail', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='UID',
            field=models.CharField(help_text='Identification tag for Squirrel sighting', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Longitude Coordinate for Squirrel sighting point', max_digits=20, max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Latitude Coordinate for Squirrel sighting point', max_digits=20, max_length=100),
        ),
    ]
